### ISSUE TITLE
The AR and IR results from qlib differ from those in the paper

### ISSUE THREAD

**Issue by yiminchi** [SJTU-DMTai/MASTER#18]
Hi, this paper is very insightful, but while trying to reproduce the results using this [repo](https://github.com/SJTU-DMTai/qlib/tree/main/examples/benchmarks/MASTER), I found that the AR and IR numbers differ from those in the paper.

_I ran bash config.sh, installed torch 1.11, and used the default settings (universe=csi300)._
``` 
IC: 0.06351523208997438 +- 0.0024514730029648597
ICIR: 0.423064812511269 +- 0.02550454001266972
Rank IC: 0.07602518910130938 +- 0.002202499642311589
Rank ICIR: 0.5101577515680222 +- 0.02116799448616885
1day.excess_return_without_cost.annualized_return: 0.17274103476104297 +- 0.009297435830790237
1day.excess_return_without_cost.information_ratio: 1.8166449194345524 +- 0.11435071760900449
```

The values for IC, ICIR, rank IC, and rank ICIR are quite similar, but I noticed some discrepancies in the AR and IR numbers. I would greatly appreciate any insights you could provide on the factors that might be contributing to these differences.

**Comment by LITONG99** [comment]
Thank you for your attention to our work. 

Since you use the Qlib version, you are training and testing the model **on different timespans** from the paper. You may want to read [An Alternative Implementation](https://github.com/SJTU-DMTai/MASTER?tab=readme-ov-file#an-alternative-qlib-implementation) in the Readme. 

Indeed, portfolio-based metrics are more sensitive to test timespan than the ranking-based metrics, such as IC. Because **AR and IR are related to the ground truth trend of stocks**, while IC focuses on ranking stocks on some specific date. For example, in a bearish market, it is hard for any model to make high profits, but an oracle model is possible to give a ranking of all stocks by their profitability. 

Although we did not test our model on this specific timespan, I would say your results make sense. Also, it is of value to systematically analyze the results according to the actual market condition and compare with other models.

**Comment by yiminchi** [comment]
Thanks a lot.

**Comment by LPeng625** [comment]
> 你好，这篇论文非常有见地，但在尝试用这个[仓库](https://github.com/SJTU-DMTai/qlib/tree/main/examples/benchmarks/MASTER)复现结果时，我发现AR和IR数值与论文中的不同。
> 
> _我运行了bash config.sh，安装了torch 1.11，并使用了默认设置（universe=csi300）。_
> 
> ```
> IC: 0.06351523208997438 +- 0.0024514730029648597
> ICIR: 0.423064812511269 +- 0.02550454001266972
> Rank IC: 0.07602518910130938 +- 0.002202499642311589
> Rank ICIR: 0.5101577515680222 +- 0.02116799448616885
> 1day.excess_return_without_cost.annualized_return: 0.17274103476104297 +- 0.009297435830790237
> 1day.excess_return_without_cost.information_ratio: 1.8166449194345524 +- 0.11435071760900449
> ```
> 
> IC、ICIR、等级IC和等级ICIR的数值相当相似，但我注意到AR和IR的数值存在一些差异。我非常感谢你能提供可能导致这些差异的因素的见解。

您好，我复现的结果，IR和AR跟原文比差2-3倍。请问做了什么额外的配置吗？谢谢，期待您的回答。
